### ISSUE TITLE
Art Works Page

### ISSUE THREAD

**Issue by SwatiKasina** [CSU-WebEngineering-Spr24/Group_ArtGalleryProject#18]
Artworks page as per figma create in react

![Image](https://github.com/CSU-WebEngineering-Spr24/Group_ArtGalleryProject/assets/157078567/ef9b2979-fe3d-43ab-9925-7ad9eda03ec7)

**Comment by Vineetha785** [comment]
#18 issue move to InProgress

![image](https://github.com/CSU-WebEngineering-Spr24/Group_ArtGalleryProject/assets/158524491/b90320b8-8130-453e-b54e-1912161cfa92)
